SELECT * FROM Account;

SELECT * FROM BOBChecked;
SELECT * FROM BOBLiked;
SELECT * FROM BOBMatches;

TRUNCATE TABLE RAYChecked;
TRUNCATE TABLE RAYLiked;
TRUNCATE TABLE RAYMatches;

DROP TABLE RAYChecked;
DROP TABLE RAYLiked;
DROP TABLE RAYMatches;

TRUNCATE TABLE Account;
DROP TABLE Account;

SELECT * FROM DEBBIEBOB;

TRUNCATE TABLE BOBRAY;
DROP TABLE BENBOB;